# Generated by Django 3.0.3 on 2020-03-05 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrenador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nombre_corredor', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('peso_kg', models.IntegerField()),
                ('altura_mts', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.TextField()),
                ('description', models.TextField()),
                ('nombre_entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entrenador.Entrenador')),
            ],
        ),
    ]
