# Generated by Django 3.0.3 on 2020-03-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_entrenamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entrenamiento', models.CharField(max_length=50)),
                ('ejercicio1', models.CharField(max_length=50)),
                ('ejercicio2', models.CharField(max_length=50)),
                ('ejercicio3', models.CharField(max_length=50)),
                ('ejercicio4', models.CharField(max_length=50)),
                ('ejercicio5', models.CharField(max_length=50)),
                ('ejercicio6', models.CharField(max_length=50)),
                ('ejercicio7', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nombre_entrenador', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('plan', models.ManyToManyField(to='entrenador.Plan_entrenamiento')),
            ],
        ),
    ]
